<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav2>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array(
                    "questions/index",
                    "Назад",
                    "style" => "color: green;"
                )); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array(
                    "questions/new",
                    "Създай ",
                    "style" => "color: green;"
                )); ?></li>
        </ul>
        </nav>
</div>

<div class="page-header">
    <h1>Резултати от търсенето</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>№</th>
            <th>Име</th>
            <th>Тип</th>
            <th>Създаден на</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $question): ?>
            <tr>
                <td><?php echo $question->id ?></td>
                <td><?php echo $question->name ?></td>
                <td><?php echo $question->type ?></td>
                <td><?php echo $question->created ?></td>

                <td><?php echo $this->tag->linkTo(array("questions/edit/" . $question->id, "Редактирай")); ?></td>
                <td><?php echo $this->tag->linkTo(array("questions/delete/" . $question->id, "Изтрий")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav2>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("questions/search", "Първа") ?></li>
                <li><?php echo $this->tag->linkTo("questions/search/" . $page->before, "Предишна") ?></li>
                <li><?php echo $this->tag->linkTo("questions/search/" . $page->next, "Следваща") ?></li>
                <li><?php echo $this->tag->linkTo("questions/search/" . $page->last, "Последна") ?></li>
            </ul>
            </nav>
    </div>
</div>
