<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("records", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit records
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "records/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFile" class="col-sm-2 control-label">File</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("file", "size" => 1000, "class" => "form-control", "id" => "fieldFile")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSub" class="col-sm-2 control-label">Subtitles</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("subtitles", "size" => 1000, "class" => "form-control", "id" => "fieldSub")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("type", "size" => 30, "class" => "form-control", "id" => "fieldType")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIP" class="col-sm-2 control-label">IP</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ip", "size" => 30, "class" => "form-control read-only", "id" => "fieldIP")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("created", "size" => 30, "class" => "form-control read-only", "id" => "fieldCreated")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
