<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Търси записи
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("records/new", "Създай запис","style"=>"")) ?>
        <?php echo $this->tag->linkTo(array("records/record", "Запиши видео","style"=>"")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "records/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">№</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "class" => "form-control", "id" => "fieldId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Име</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFile" class="col-sm-2 control-label">Файл</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("file", "size" => 30, "class" => "form-control", "id" => "fieldFile")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Тип</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("type", "size" => 30, "class" => "form-control", "id" => "fieldType")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIP" class="col-sm-2 control-label">IP</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ip", "size" => 20, "class" => "form-control", "id" => "fieldIP")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">Създадено на</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("created", "size" => 30, "class" => "form-control", "id" => "fieldCreated")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Търси", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
