<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav2>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array(
                    "records",
                    "Go Back",
                    "class" => "btn-primary text-primary btn",
                    "style" => "color: green;"
                )) ?></li>
        </ul>
        </nav>
</div>

<div class="page-header">
    <h1>
        Създай запис
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    array(
        "records/create",
        "autocomplete" => "off",
        "class"        => "form-horizontal"
    )
);
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Име</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFile" class="col-sm-2 control-label">Файл</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("file", "size" => 30, "class" => "form-control", "id" => "fieldFile")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSub" class="col-sm-2 control-label">Субтитри</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array(
            "subtitles",
            "size"  => 30,
            "class" => "form-control",
            "id"    => "fieldSub"
        )) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Тип</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("type", "size" => 30, "class" => "form-control", "id" => "fieldType")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIP" class="col-sm-2 control-label">IP</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array(
            "ip",
            "size"     => 20,
            "class"    => "form-control",
            "id"       => "fieldIP",
            "disabled" => "true"
        )) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">Създадено на</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array(
            "created",
            "size"     => 30,
            "class"    => "form-control",
            "id"       => "fieldCreated",
            "disabled" => "true"
        )) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Запис", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
