<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav2>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array(
                    "records/index",
                    "Назад",
                    "style" => "color: green;"
                )); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array(
                    "records/new",
                    "Създай",
                    "style" => "color: green;"
                )); ?></li>
        </ul>
        </nav>
</div>

<div class="page-header">
    <h1>Резултати</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>№</th>
            <th>Име (Файл)</th>
            <th>Тип</th>
            <th>IP</th>
            <th>Създаден на</th>

            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $record): ?>
            <tr>
                <td><?php echo $record->id ?></td>
                <td title="<?php echo $record->file ?>"><?php echo $record->name ?></td>
                <td><?php echo $record->type ?></td>
                <td><?php echo $record->ip ?></td>
                <td><?php echo $record->created ?></td>

                <td><?php echo $this->tag->linkTo(array("records/view/" . $record->id, "Преглед")); ?></td>
                <td><?php echo $this->tag->linkTo(array("records/edit/" . $record->id, "Редакция")); ?></td>
                <td><?php echo $this->tag->linkTo(array("records/delete/" . $record->id, "Изтрий")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav2>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("records/search", "Първа") ?></li>
                <li><?php echo $this->tag->linkTo("records/search/" . $page->before, "Предишна") ?></li>
                <li><?php echo $this->tag->linkTo("records/search/" . $page->next, "Следваща") ?></li>
                <li><?php echo $this->tag->linkTo("records/search/" . $page->last, "Последна") ?></li>
            </ul>
            </nav>
    </div>
</div>
